IF OBJECT_ID('dbo.MM_USER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MM_USER
    (
        USER_ID UNIQUEIDENTIFIER NOT NULL,
        FULL_NAME NVARCHAR(255) NOT NULL,
        EMAIL NVARCHAR(255) NOT NULL,
        PASSWORD_HASH NVARCHAR(MAX) NULL,
        PASSWORD_SALT NVARCHAR(MAX) NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_MM_USER_USER_ID
            PRIMARY KEY (USER_ID)
    );
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UIX_MM_USER_EMAIL'
    AND object_id = OBJECT_ID('dbo.MM_USER')
)
BEGIN
    CREATE UNIQUE INDEX UIX_MM_USER_EMAIL
    ON dbo.MM_USER(EMAIL);
END;

IF OBJECT_ID('dbo.MM_PROJECT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MM_PROJECT
    (
        PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
        USER_ID UNIQUEIDENTIFIER NOT NULL,
        NAME NVARCHAR(255) NOT NULL,
        DESCRIPTION NVARCHAR(MAX) NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_MM_PROJECT_PROJECT_ID
            PRIMARY KEY (PROJECT_ID),

        CONSTRAINT FK_MM_PROJECT_MM_USER
            FOREIGN KEY (USER_ID)
            REFERENCES dbo.MM_USER(USER_ID)
    );
END;

IF OBJECT_ID('dbo.DE_PROJECT_COLUMN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_PROJECT_COLUMN
    (
        PROJECT_COLUMN_ID UNIQUEIDENTIFIER NOT NULL,
        PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
        NAME NVARCHAR(100) NOT NULL,
        POSITION INT NOT NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_PROJECT_COLUMN_COLUMN_ID
            PRIMARY KEY (PROJECT_COLUMN_ID),

        CONSTRAINT FK_DE_PROJECT_COLUMN_MM_PROJECT
            FOREIGN KEY (PROJECT_ID)
            REFERENCES dbo.MM_PROJECT(PROJECT_ID)
    );
END;

IF OBJECT_ID('dbo.MM_PROJECT_TAG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MM_PROJECT_TAG
    (
        PROJECT_TAG_ID UNIQUEIDENTIFIER NOT NULL,
        PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
        NAME NVARCHAR(100) NOT NULL,
        COLOR NVARCHAR(MAX) NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_MM_PROJECT_TAG_TAG_ID
            PRIMARY KEY (PROJECT_TAG_ID),

        CONSTRAINT FK_MM_PROJECT_TAG_MM_PROJECT
            FOREIGN KEY (PROJECT_ID)
            REFERENCES dbo.MM_PROJECT(PROJECT_ID)
    );
END;

IF OBJECT_ID('dbo.DE_PROJECT_COLLABORATOR', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_PROJECT_COLLABORATOR
    (
        PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
        USER_ID UNIQUEIDENTIFIER NOT NULL,
        ROLE NVARCHAR(50) NOT NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_PROJECT_COLLABORATOR
            PRIMARY KEY (PROJECT_ID, USER_ID),

        CONSTRAINT FK_DE_PROJECT_COLLABORATOR_MM_PROJECT
            FOREIGN KEY (PROJECT_ID)
            REFERENCES dbo.MM_PROJECT(PROJECT_ID),

        CONSTRAINT FK_DE_PROJECT_COLLABORATOR_MM_USER
            FOREIGN KEY (USER_ID)
            REFERENCES dbo.MM_USER(USER_ID)
    );
END;

IF OBJECT_ID('dbo.DE_TASK_ITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_TASK_ITEM
    (
        TASK_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
        TITLE NVARCHAR(255) NOT NULL,
        DESCRIPTION NVARCHAR(MAX) NULL,
        BOARD_TYPE NVARCHAR(50) NULL,

        PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
        PROJECT_COLUMN_ID UNIQUEIDENTIFIER NOT NULL,
        ASSIGNED_USER_ID UNIQUEIDENTIFIER NULL,

        START_DATE DATETIME NULL,
        DUE_DATE DATETIME NULL,

        PRIORITY NVARCHAR(50) NOT NULL,
        CATEGORY NVARCHAR(100) NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_TASK_ITEM_TASK_ITEM_ID
            PRIMARY KEY (TASK_ITEM_ID),

        CONSTRAINT FK_DE_TASK_ITEM_MM_PROJECT
            FOREIGN KEY (PROJECT_ID)
            REFERENCES dbo.MM_PROJECT(PROJECT_ID),

        CONSTRAINT FK_DE_TASK_ITEM_DE_PROJECT_COLUMN
            FOREIGN KEY (PROJECT_COLUMN_ID)
            REFERENCES dbo.DE_PROJECT_COLUMN(PROJECT_COLUMN_ID),

        CONSTRAINT FK_DE_TASK_ITEM_MM_USER
            FOREIGN KEY (ASSIGNED_USER_ID)
            REFERENCES dbo.MM_USER(USER_ID)
    );
END;

IF OBJECT_ID('dbo.DE_TASK_ITEM_TAG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_TASK_ITEM_TAG
    (
        TASK_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
        PROJECT_TAG_ID UNIQUEIDENTIFIER NOT NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_TASK_ITEM_TAG
            PRIMARY KEY (TASK_ITEM_ID, PROJECT_TAG_ID),

        CONSTRAINT FK_DE_TASK_ITEM_TAG_DE_TASK_ITEM
            FOREIGN KEY (TASK_ITEM_ID)
            REFERENCES dbo.DE_TASK_ITEM(TASK_ITEM_ID),

        CONSTRAINT FK_DE_TASK_ITEM_TAG_MM_PROJECT_TAG
            FOREIGN KEY (PROJECT_TAG_ID)
            REFERENCES dbo.MM_PROJECT_TAG(PROJECT_TAG_ID)
    );
END;

IF OBJECT_ID('dbo.DE_TASK_ATTACHMENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_TASK_ATTACHMENT
    (
        TASK_ATTACHMENT_ID UNIQUEIDENTIFIER NOT NULL,
        TASK_ITEM_ID UNIQUEIDENTIFIER NOT NULL,

        FILE_NAME NVARCHAR(1024) NOT NULL,
        FILE_PATH NVARCHAR(MAX) NOT NULL,
        FILE_TYPE NVARCHAR(255) NULL,
        FILE_SIZE BIGINT NOT NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_TASK_ATTACHMENT_ATTACHMENT_ID
            PRIMARY KEY (TASK_ATTACHMENT_ID),

        CONSTRAINT FK_DE_TASK_ATTACHMENT_DE_TASK_ITEM
            FOREIGN KEY (TASK_ITEM_ID)
            REFERENCES dbo.DE_TASK_ITEM(TASK_ITEM_ID)
    );
END;

IF OBJECT_ID('dbo.DE_TASK_CHECKLIST_ITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_TASK_CHECKLIST_ITEM
    (
        TASK_CHECKLIST_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
        TASK_ITEM_ID UNIQUEIDENTIFIER NOT NULL,

        LABEL NVARCHAR(500) NOT NULL,
        IS_COMPLETED BIT NOT NULL DEFAULT 0,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_TASK_CHECKLIST_ITEM_CHECKLIST_ID
            PRIMARY KEY (TASK_CHECKLIST_ITEM_ID),

        CONSTRAINT FK_DE_TASK_CHECKLIST_ITEM_DE_TASK_ITEM
            FOREIGN KEY (TASK_ITEM_ID)
            REFERENCES dbo.DE_TASK_ITEM(TASK_ITEM_ID)
    );
END;

IF OBJECT_ID('dbo.DE_TASK_ASSIGNEE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DE_TASK_ASSIGNEE
    (
        TASK_ITEM_ID UNIQUEIDENTIFIER NOT NULL,
        USER_ID UNIQUEIDENTIFIER NOT NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_DE_TASK_ASSIGNEE
            PRIMARY KEY (TASK_ITEM_ID, USER_ID),

        CONSTRAINT FK_DE_TASK_ASSIGNEE_DE_TASK_ITEM
            FOREIGN KEY (TASK_ITEM_ID)
            REFERENCES dbo.DE_TASK_ITEM(TASK_ITEM_ID),

        CONSTRAINT FK_DE_TASK_ASSIGNEE_MM_USER
            FOREIGN KEY (USER_ID)
            REFERENCES dbo.MM_USER(USER_ID)
    );
END;

IF OBJECT_ID('dbo.MM_CUSTOMER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MM_CUSTOMER
    (
        CUSTOMER_ID INT IDENTITY(1,1) NOT NULL,

        NAME NVARCHAR(255) NOT NULL,
        EMAIL NVARCHAR(255) NOT NULL,
        PHONE NVARCHAR(50) NOT NULL,

        ADDRESS NVARCHAR(MAX) NULL,
        CITY NVARCHAR(100) NULL,
        STATE NVARCHAR(100) NULL,
        POSTAL_CODE NVARCHAR(20) NULL,
        COUNTRY NVARCHAR(100) NULL,

        RECORD_TYP INT NOT NULL DEFAULT 1,
        CREATED_BY NVARCHAR(50) NOT NULL,
        CREATED_DATE DATETIME NOT NULL,
        CREATED_LOC NVARCHAR(15) NULL,
        UPDATED_BY NVARCHAR(50) NULL,
        UPDATED_DATE DATETIME NULL,
        UPDATED_LOC NVARCHAR(15) NULL,

        CONSTRAINT PK_MM_CUSTOMER_CUSTOMER_ID
            PRIMARY KEY (CUSTOMER_ID)
    );
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_MM_PROJECT_USER_ID'
    AND object_id = OBJECT_ID('dbo.MM_PROJECT')
)
BEGIN
    CREATE INDEX IX_MM_PROJECT_USER_ID
    ON dbo.MM_PROJECT(USER_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_PROJECT_COLUMN_PROJECT_ID'
    AND object_id = OBJECT_ID('dbo.DE_PROJECT_COLUMN')
)
BEGIN
    CREATE INDEX IX_DE_PROJECT_COLUMN_PROJECT_ID
    ON dbo.DE_PROJECT_COLUMN(PROJECT_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_MM_PROJECT_TAG_PROJECT_ID'
    AND object_id = OBJECT_ID('dbo.MM_PROJECT_TAG')
)
BEGIN
    CREATE INDEX IX_MM_PROJECT_TAG_PROJECT_ID
    ON dbo.MM_PROJECT_TAG(PROJECT_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_PROJECT_COLLABORATOR_USER_ID'
    AND object_id = OBJECT_ID('dbo.DE_PROJECT_COLLABORATOR')
)
BEGIN
    CREATE INDEX IX_DE_PROJECT_COLLABORATOR_USER_ID
    ON dbo.DE_PROJECT_COLLABORATOR(USER_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_ITEM_PROJECT_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_ITEM')
)
BEGIN
    CREATE INDEX IX_DE_TASK_ITEM_PROJECT_ID
    ON dbo.DE_TASK_ITEM(PROJECT_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_ITEM_PROJECT_COLUMN_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_ITEM')
)
BEGIN
    CREATE INDEX IX_DE_TASK_ITEM_PROJECT_COLUMN_ID
    ON dbo.DE_TASK_ITEM(PROJECT_COLUMN_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_ITEM_ASSIGNED_USER_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_ITEM')
)
BEGIN
    CREATE INDEX IX_DE_TASK_ITEM_ASSIGNED_USER_ID
    ON dbo.DE_TASK_ITEM(ASSIGNED_USER_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_ITEM_TAG_PROJECT_TAG_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_ITEM_TAG')
)
BEGIN
    CREATE INDEX IX_DE_TASK_ITEM_TAG_PROJECT_TAG_ID
    ON dbo.DE_TASK_ITEM_TAG(PROJECT_TAG_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_ATTACHMENT_TASK_ITEM_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_ATTACHMENT')
)
BEGIN
    CREATE INDEX IX_DE_TASK_ATTACHMENT_TASK_ITEM_ID
    ON dbo.DE_TASK_ATTACHMENT(TASK_ITEM_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_CHECKLIST_ITEM_TASK_ITEM_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_CHECKLIST_ITEM')
)
BEGIN
    CREATE INDEX IX_DE_TASK_CHECKLIST_ITEM_TASK_ITEM_ID
    ON dbo.DE_TASK_CHECKLIST_ITEM(TASK_ITEM_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DE_TASK_ASSIGNEE_USER_ID'
    AND object_id = OBJECT_ID('dbo.DE_TASK_ASSIGNEE')
)
BEGIN
    CREATE INDEX IX_DE_TASK_ASSIGNEE_USER_ID
    ON dbo.DE_TASK_ASSIGNEE(USER_ID);
END;

IF NOT EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_MM_CUSTOMER_EMAIL'
    AND object_id = OBJECT_ID('dbo.MM_CUSTOMER')
)
BEGIN
    CREATE INDEX IX_MM_CUSTOMER_EMAIL
    ON dbo.MM_CUSTOMER(EMAIL);
END;

INSERT INTO dbo.MM_CUSTOMER
(
    NAME,
    EMAIL,
    PHONE,
    ADDRESS,
    CITY,
    STATE,
    POSTAL_CODE,
    COUNTRY,
    CREATED_BY,
    CREATED_DATE,
    CREATED_LOC,
    UPDATED_BY,
    UPDATED_DATE,
    UPDATED_LOC
)
VALUES
('Acme Corporation',      'contact@acme.com',      '555-1001', '123 Main St',      'New York',      'NY', '10001', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Global Tech',           'info@globaltech.com',   '555-1002', '456 Oak Ave',      'Los Angeles',   'CA', '90001', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Sunrise Trading',       'sales@sunrise.com',     '555-1003', '789 Pine Rd',      'Chicago',       'IL', '60601', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Blue Sky Solutions',    'hello@bluesky.com',     '555-1004', '321 Cedar Blvd',   'Houston',       'TX', '77001', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Prime Industries',      'support@prime.com',     '555-1005', '654 Maple Dr',     'Phoenix',       'AZ', '85001', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Evergreen Supplies',    'contact@evergreen.com', '555-1006', '987 Birch Ln',     'Seattle',       'WA', '98101', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Metro Logistics',       'admin@metro.com',       '555-1007', '258 Walnut St',    'Dallas',        'TX', '75201', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('NextGen Software',      'team@nextgen.com',      '555-1008', '147 Spruce Ct',    'Boston',        'MA', '02108', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Green Energy Ltd',      'info@greenenergy.com',  '555-1009', '369 Elm St',       'Denver',        'CO', '80201', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL),
('Future Vision Inc',     'office@futurevision.com','555-1010','741 Aspen Way',    'Miami',         'FL', '33101', 'USA', 'SYSTEM', GETDATE(), '127.0.0.1', NULL, NULL, NULL);
