-- ============================================================================
-- DATABASE STANDARDIZATION MIGRATION SCRIPT
-- ============================================================================
-- Description: Standardizes all tables, columns, constraints, and indexes
--              according to the Database Standardization Guidelines.
-- ============================================================================

-- Drop incorrect case-sensitive tables from previous migration attempts
-- DROP TABLE IF EXISTS DE_TASK_ASSIGNEE CASCADE;
-- DROP TABLE IF EXISTS DE_TASK_CHECKLIST_ITEM CASCADE;
-- DROP TABLE IF EXISTS DE_TASK_ATTACHMENT CASCADE;
-- DROP TABLE IF EXISTS DE_TASK_ITEM_TAG CASCADE;
-- DROP TABLE IF EXISTS DE_TASK_ITEM CASCADE;
-- DROP TABLE IF EXISTS DE_PROJECT_COLLABORATOR CASCADE;
-- DROP TABLE IF EXISTS MM_PROJECT_TAG CASCADE;
-- DROP TABLE IF EXISTS DE_PROJECT_COLUMN CASCADE;
-- DROP TABLE IF EXISTS MM_PROJECT CASCADE;
-- DROP TABLE IF EXISTS MM_USER CASCADE;
-- DROP TABLE IF EXISTS MM_CUSTOMER CASCADE;

CREATE TABLE IF NOT EXISTS "MM_USER" (
    "USER_ID" UUID NOT NULL,
    "FULL_NAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "PASSWORD_HASH" TEXT NULL,
    "PASSWORD_SALT" TEXT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_MM_USER_USER_ID" PRIMARY KEY ("USER_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UIX_MM_USER_EMAIL_LOWER" ON "MM_USER" (LOWER("EMAIL"));

CREATE TABLE IF NOT EXISTS "MM_PROJECT" (
    "PROJECT_ID" UUID NOT NULL,
    "USER_ID" UUID NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" TEXT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_MM_PROJECT_PROJECT_ID" PRIMARY KEY ("PROJECT_ID"),
    CONSTRAINT "FK_MM_PROJECT_MM_USER" FOREIGN KEY ("USER_ID")
        REFERENCES "MM_USER" ("USER_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DE_PROJECT_COLUMN" (
    "PROJECT_COLUMN_ID" UUID NOT NULL,
    "PROJECT_ID" UUID NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "POSITION" INTEGER NOT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_PROJECT_COLUMN_COLUMN_ID" PRIMARY KEY ("PROJECT_COLUMN_ID"),
    CONSTRAINT "FK_DE_PROJECT_COLUMN_MM_PROJECT" FOREIGN KEY ("PROJECT_ID")
        REFERENCES "MM_PROJECT" ("PROJECT_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MM_PROJECT_TAG" (
    "PROJECT_TAG_ID" UUID NOT NULL,
    "PROJECT_ID" UUID NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "COLOR" TEXT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_MM_PROJECT_TAG_TAG_ID" PRIMARY KEY ("PROJECT_TAG_ID"),
    CONSTRAINT "FK_MM_PROJECT_TAG_MM_PROJECT" FOREIGN KEY ("PROJECT_ID")
        REFERENCES "MM_PROJECT" ("PROJECT_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DE_PROJECT_COLLABORATOR" (
    "PROJECT_ID" UUID NOT NULL,
    "USER_ID" UUID NOT NULL,
    "ROLE" VARCHAR(50) NOT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_PROJECT_COLLABORATOR" PRIMARY KEY ("PROJECT_ID", "USER_ID"),
    CONSTRAINT "FK_DE_PROJECT_COLLABORATOR_MM_PROJECT" FOREIGN KEY ("PROJECT_ID")
        REFERENCES "MM_PROJECT" ("PROJECT_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_DE_PROJECT_COLLABORATOR_MM_USER" FOREIGN KEY ("USER_ID")
        REFERENCES "MM_USER" ("USER_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DE_TASK_ITEM" (
    "TASK_ITEM_ID" UUID NOT NULL,
    "TITLE" VARCHAR(255) NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "BOARD_TYPE" VARCHAR(50) NULL,
    "PROJECT_ID" UUID NOT NULL,
    "PROJECT_COLUMN_ID" UUID NOT NULL,
    "ASSIGNED_USER_ID" UUID NULL,
    "START_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "DUE_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "PRIORITY" VARCHAR(50) NOT NULL,
    "CATEGORY" VARCHAR(100) NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_TASK_ITEM_TASK_ITEM_ID" PRIMARY KEY ("TASK_ITEM_ID"),
    CONSTRAINT "FK_DE_TASK_ITEM_MM_PROJECT" FOREIGN KEY ("PROJECT_ID")
        REFERENCES "MM_PROJECT" ("PROJECT_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_DE_TASK_ITEM_DE_PROJECT_COLUMN" FOREIGN KEY ("PROJECT_COLUMN_ID")
        REFERENCES "DE_PROJECT_COLUMN" ("PROJECT_COLUMN_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_DE_TASK_ITEM_MM_USER" FOREIGN KEY ("ASSIGNED_USER_ID")
        REFERENCES "MM_USER" ("USER_ID")
);

CREATE TABLE IF NOT EXISTS DE_TASK_ITEM_TAG (
    "TASK_ITEM_ID" UUID NOT NULL,
    "PROJECT_TAG_ID" UUID NOT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_TASK_ITEM_TAG" PRIMARY KEY ("TASK_ITEM_ID", "PROJECT_TAG_ID"),
    CONSTRAINT "FK_DE_TASK_ITEM_TAG_DE_TASK_ITEM" FOREIGN KEY ("TASK_ITEM_ID")
        REFERENCES "DE_TASK_ITEM" ("TASK_ITEM_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_DE_TASK_ITEM_TAG_MM_PROJECT_TAG" FOREIGN KEY ("PROJECT_TAG_ID")
        REFERENCES "MM_PROJECT_TAG" ("PROJECT_TAG_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DE_TASK_ATTACHMENT" (
    "TASK_ATTACHMENT_ID" UUID NOT NULL,
    "TASK_ITEM_ID" UUID NOT NULL,
    "FILE_NAME" VARCHAR(1024) NOT NULL,
    "FILE_PATH" TEXT NOT NULL,
    "FILE_TYPE" VARCHAR(255) NULL,
    "FILE_SIZE" BIGINT NOT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_TASK_ATTACHMENT_ATTACHMENT_ID" PRIMARY KEY ("TASK_ATTACHMENT_ID"),
    CONSTRAINT "FK_DE_TASK_ATTACHMENT_DE_TASK_ITEM" FOREIGN KEY ("TASK_ITEM_ID")
        REFERENCES "DE_TASK_ITEM" ("TASK_ITEM_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DE_TASK_CHECKLIST_ITEM" (
    "TASK_CHECKLIST_ITEM_ID" UUID NOT NULL,
    "TASK_ITEM_ID" UUID NOT NULL,
    "LABEL" VARCHAR(500) NOT NULL,
    "IS_COMPLETED" BOOLEAN NOT NULL DEFAULT false,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_TASK_CHECKLIST_ITEM_CHECKLIST_ID" PRIMARY KEY ("TASK_CHECKLIST_ITEM_ID"),
    CONSTRAINT "FK_DE_TASK_CHECKLIST_ITEM_DE_TASK_ITEM" FOREIGN KEY ("TASK_ITEM_ID")
        REFERENCES "DE_TASK_ITEM" ("TASK_ITEM_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "DE_TASK_ASSIGNEE" (
    "TASK_ITEM_ID" UUID NOT NULL,
    "USER_ID" UUID NOT NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_DE_TASK_ASSIGNEE" PRIMARY KEY ("TASK_ITEM_ID", "USER_ID"),
    CONSTRAINT "FK_DE_TASK_ASSIGNEE_DE_TASK_ITEM" FOREIGN KEY ("TASK_ITEM_ID")
        REFERENCES "DE_TASK_ITEM" ("TASK_ITEM_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_DE_TASK_ASSIGNEE_MM_USER" FOREIGN KEY ("USER_ID")
        REFERENCES "MM_USER" ("USER_ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MM_CUSTOMER" (
    "CUSTOMER_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "PHONE" VARCHAR(50) NOT NULL,
    "ADDRESS" TEXT NULL,
    "CITY" VARCHAR(100) NULL,
    "STATE" VARCHAR(100) NULL,
    "POSTAL_CODE" VARCHAR(20) NULL,
    "COUNTRY" VARCHAR(100) NULL,
    
    "RECORD_TYP" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY" VARCHAR(50) NOT NULL,
    "CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CREATED_LOC" VARCHAR(15) NULL,
    "UPDATED_BY" VARCHAR(50) NULL,
    "UPDATED_DATE" TIMESTAMP WITH TIME ZONE NULL,
    "UPDATED_LOC" VARCHAR(15) NULL,
    
    CONSTRAINT "PK_MM_CUSTOMER_CUSTOMER_ID" PRIMARY KEY ("CUSTOMER_ID")
);